FROM node:22-alpine

RUN apk add --no-cache vips-dev build-base python3 git \
    && corepack enable \
    && corepack prepare yarn@4.9.1 --activate

WORKDIR /app

# Копируем только package.json + lockfile
COPY package.json yarn.lock ./

RUN yarn install --immutable

COPY . .

EXPOSE 3000
CMD ["yarn", "dev"]